### ISSUE TITLE
[cli] `art fmt` panics

### ISSUE THREAD

**Issue by matthiasbeyer** [vitiral/artifact#219]
* `art fmt` panics:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Load("Overlapping key found <REQ-libimagentrylink> other key at: /home/m/archive/development/rust/imag/design/lib/entry/libimagentrylink.toml"), State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

* `art fmt -l` panics:

```
## running fmt
thread 'main' panicked at 'unexpected new file: /home/m/archive/development/rust/imag/design/bin/domain/imag-project.toml', /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/artifact-app-1.1.0-beta001/src/cmd/fmt.rs:111:24
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

* `art fmt -d` panics:

```
## running fmt
thread 'main' panicked at 'unexpected new file: /home/m/archive/development/rust/imag/design/lib/core.toml', /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/artifact-app-1.1.0-beta001/src/cmd/fmt.rs:111:24
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by vitiral** [comment]
Are the errors *themselves* expected? Why is a new file appearing?

The panic will be resolved with #222.

**Comment by matthiasbeyer** [comment]
These panics result from running a `art fmt -w` (was it -w? Am on mobile, cannot check) which creates the markdown files formatted, but as toml files. I created an issue for this separately, as I remember. 

So the error is expected, though not as a panic but as a clean error log and exit.

**Comment by vitiral** [comment]
I believe this should be fixed. Let me know if not.
